### ISSUE TITLE
Muse does not function

### ISSUE THREAD

**Issue by slaapkopamy** [museofficial/muse#1258]
**What's happening?**
I recently setup a clean installation of muse using docker compose file pulling the latest version (2.11.1), I inserted the api keys for youtube and spotify in the bot with ofcourse my bot token. started the bot up and invited the bot in my server. now i wanted to test the functionality of the bot by adding a spotify url in the play command to findout it's getting errored with ope: song not found, tried with a different url.. same thing. tried with just searching... guess what... same thing...
if i try with a youtube url i get 403 forbidden (probably something on google side since i cant access the api key on my pc either)

**Logs**
For some reason, there are no logs being produced in the docker container. if i run docker compose logs -f the only last thing i see is the discord invite url for the bot.

**Screenshots**
discord: https://slaapkopamy.com/sc/images/lJoRssyXbJ8FXjBr8SY4z.png
docker: https://slaapkopamy.com/sc/images/Y3NrZ4SoFvrCgdysphmkC.png

**Additional context**

**Runtime**
I'm running Muse:
- [ ] Directly from the cloned repository
- [x ] Inside a Docker container
- [ ] Something else (please elaborate)

**Versions**
- Muse: 2.11.1
- Docker (if applicable): 28.0.4 build v8034c0
- OS: ubuntu 20.4.6 lts
- Node.js: (if running outside the Docker container)
- ffmpeg: (if running outside the Docker container, 4.1 or later is required)

**Comment by melzyy** [comment]
try #1255

**Comment by slaapkopamy** [comment]
> try [#1255](https://github.com/museofficial/muse/issues/1255)

Sadly tried and same issue, also the docker container does not produce any logs

**Comment by a-sitarz** [comment]
Got the same issue.
Looks like YT changed something, again...

**Comment by nealhead** [comment]
Are we done for? Do any self hosted music bots still work?

**Comment by JordiBrisbois** [comment]
Dirty fix while waiting for [this pull request](https://github.com/distubejs/ytdl-core/pull/251) to be merged.

If you're using Docker, mount /usr/ as a volume:

```
services:
  muse:
    image: 'ghcr.io/museofficial/muse:pr-1256'
    restart: always
    volumes:
      - 'bot-data-muse:/data'
      - 'bot-datanode-muse:/usr/'
    environment:
      - DISCORD_TOKEN=xxx
      - YOUTUBE_API_KEY=xxx
      - SPOTIFY_CLIENT_ID=xxx
      - SPOTIFY_CLIENT_SECRET=xxx
volumes:
  bot-data-muse: null
  bot-datanode-muse: null
```
Next, edit /app/node_modules/@distube/ytdl-core/lib/sig.js inside the container and replace its contents with the code from:

https://raw.githubusercontent.com/distubejs/ytdl-core/ba7516dd4f5ad125f9ee8a41ebea486442533f82/lib/sig.js

Save the file, restart your container, and it should work.

**Comment by rexyness** [comment]
`ghcr.io/museofficial/muse:pr-1256` can be used without the dirty fixed as of now ^_^

**Comment by ChrisTecha** [comment]
> `ghcr.io/museofficial/muse:pr-1256` can be used without the dirty fixed as of now ^_^

working for me

**Comment by Maikel1990** [comment]
> `ghcr.io/museofficial/muse:pr-1256` can be used without the dirty fixed as of now ^_^

 Working for me for Youtube search results/links. Spotify links gives me a no songs found error.

**Comment by DejaVuMan** [comment]
@Maikel1990 , that seems like a separate issue - I just loaded a custom spotify playlist with no issues using branch ```pr-1256```.

![Image](https://github.com/user-attachments/assets/423e8463-8761-4def-a848-42140bc70785)

**Comment by slaapkopamy** [comment]
> [@slaapkopamy](https://github.com/slaapkopamy) Since the fix has been merged, you should close this issue unless you can still reproduce the issue in latest version

I still have the same issue,

pulled the pr1261 image. rechecked the api keys and secrets if they are still valid (they are).
loaded up the bot via docker compose up -d, checked after that the logs to see if there are any errors (none).
did /play in the discord with a random query, got the same error as explained earlier. tried with a spotify url, same issue and tried with youtube url, same issue.

If my server ip is blocked I should receive a different error right? then only ope 403 on youtube and ope on spotify?

**Comment by Mubelotix** [comment]
Maybe you could try running it with `yarn` outside of docker after cloning the repository. Either it would work, or that would give us logs with more information

**Comment by slaapkopamy** [comment]
> Maybe you could try running it with `yarn` outside of docker after cloning the repository. Either it would work, or that would give us logs with more information

I can use nodejs 24 for it?
Currently on the machine 14 is installed

**Comment by Happyllama25** [comment]
Running latest still shows the same issue (stream error) but using pr-1256 solves the issue, has pr-1256 been updated since being merged??

**Comment by Happyllama25** [comment]
> @slaapkopamy Since the fix has been merged, you should close this issue unless you can still reproduce the issue in latest version

Has it been merged? I cannot find evidence of this happening

https://github.com/museofficial/muse/releases/tag/v2.11.0
v2.11.0 updated to ytdl-core to 4.16.5 but remains broken

https://github.com/museofficial/muse/pull/1256
pr-1256 bumps it up to 4.16.9 making muse usable

**Comment by shiftybitshiftr** [comment]
This is worth retesting on v2.11.3.

The YouTube/Spotify playback symptoms discussed here overlap heavily with the old `@distube/ytdl-core` failure path and the unofficial workaround images people were using. v2.11.3 replaces the brittle playback extraction path with `yt-dlp` and publishes updated official Docker images.

Please pull a current official image and restart:

```sh
docker compose pull
docker compose up -d
```

Official tags:

```text
ghcr.io/museofficial/muse:2.11.3
codetheweb/muse:2.11.3
```

I’m leaving this open for confirmation because the issue includes a mix of YouTube, Spotify, and “no logs” reports. If this still reproduces on v2.11.3 or newer, please comment with the startup `Running version ...` line, the exact URL/query used, whether it is YouTube or Spotify, and fresh logs.

**Comment by shiftybitshiftr** [comment]
Closing this because there has been no follow-up after the v2.11.3 retest request. If this still reproduces on v2.11.3 or newer, please open a fresh issue with the startup `Running version ...` line, image tag/digest or install method, host architecture, the exact URL/query/command, and fresh logs.
